name: "Stackforge Forge"
description: "Forge your infrastructure"
branding:
  icon: 'cloud'
  color: 'blue'
inputs:
  config_file:
    description: "Stackforge's config file"
    required: true
  api_key: 
    description: "Stackforge's API key"
    required: true
  stage:
    description: "The stage you're deploying to"
    required: true
outputs:
  infra_outputs:
    description: "The infra step outputs"
runs:
  using: 'docker'
  image: 'Dockerfile'
